### ISSUE TITLE
use *bool as nullable boolean

### ISSUE THREAD

**Issue by TomasVojacek** [imdario/mergo#127] opened 2019-10-30 22:41 UTC
proposal use *bool as nullable boolean
mergo will copy any not nil value to dst

index 3fb6c64..80e733b 100644
--- a/merge.go
+++ b/merge.go
@@ -170,6 +170,13 @@ func deepMerge(dst, src reflect.Value, visited map[uintptr]*visit, depth int, co
                        dst.Set(reflect.AppendSlice(dst, src))
                }
        case reflect.Ptr:
+               if src.IsNil() {
+                       break
+               }
+               if dst.Elem().Kind()==reflect.Bool{
+                       dst.Set(src)
+                       break
+               }
                fallthrough
        case reflect.Interface:
                if src.IsNil() {

**Comment by JackQuincy** [comment] 2019-12-02 17:32
This broke my team on the latest vendor after this change https://github.com/imdario/mergo/pull/120 before we could use a *bool to allow false to overwrite true. But with that change it no longer works.  I'd like it if mergo can look at the pointer and see if the Elem().Kind() is a native type(not pointer or struct? or just int, bool etc.) and allow zero value to overwrite a non zero value. And make nil the value that doesn't merge.  For now we are going to have to switch from *bool to *enum that has 'true', 'false', and a zero value 'invalid'

**Comment by github4jiawen** [comment] 2019-12-08 14:31
Duplicate of #89

**Comment by imdario** [comment] 2020-05-17 14:45
I don't think this is really a duplicate of #89, but a duplicate of #131 

@JackQuincy sorry for the issue, you should be able to go back to merge bool pointers using `mergo.WithOverwriteWithEmptyValue` in next release 0.3.10. Actually, you won't need to use bool pointers, as this affects any false value that is going to be merge.

**Closed by imdario** 2020-05-17 14:45 UTC
