### ISSUE TITLE
Merge Boolean

### ISSUE THREAD

**Issue by quentinalbertone** [imdario/mergo#129] opened 2019-11-26 14:02 UTC
Hello, 

I would like to `mergo.merge` two struct which contain boolean. It works well when I replace the actual value with `true` but not the opposite. I suppose that `false` is the default value for boolean variables and it is also the zero value.
Could you tell me how to replace the boolean please

```Golang
type Foo struct {
	A bool
	B bool
}

func main() {
	src := Foo{
		A: true,
		B: false,
	}
	dest := Foo{
		A: false,
		B: true,
	}
	mergo.Merge(&dest, src)
	fmt.Println(dest)
	// Will print
	// {true true}
        // I would like {true false}
}
```
I may be confusing the main purpose of mergo ?

Thanks

**Comment by github4jiawen** [comment] 2019-12-08 14:30
Duplicate of #89

**Comment by imdario** [comment] 2020-05-17 15:00
@quentinalbertone As stated in the README:

> You can only merge same-type structs with exported fields initialized as zero value of their type and same-types maps.

What you want is to override dest.B with a zero value, so you are going to need `mergo.WithOverwriteWithEmptyValue`. I pushed a test for your case to show how to use it:

```go
func TestIssue129Boolean(t *testing.T) {
	type Foo struct {
		A bool
		B bool
	}

	src := Foo{
		A: true,
		B: false,
	}
	dst := Foo{
		A: false,
		B: true,
	}

	// Standard behavior
	if err := Merge(&dst, src); err != nil {
		t.Fatal(err)
	}
	if dst.A != true {
		t.Fatalf("expected true, got false")
	}
	if dst.B != true {
		t.Fatalf("expected true, got false")
	}

	// Expected behavior
	dst = Foo{
		A: false,
		B: true,
	}
	if err := Merge(&dst, src, WithOverwriteWithEmptyValue); err != nil {
		t.Fatal(err)
	}
	if dst.A != true {
		t.Fatalf("expected true, got false")
	}
	if dst.B != false {
		t.Fatalf("expected false, got true")
	}
}
```

**Closed by imdario** 2020-05-17 15:00 UTC
